import type { Metadata } from "next";
import { Geist, Geist_Mono, Crimson_Pro } from "next/font/google";
import "./globals.css";
import { Player } from "@/components/player";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Tarun's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${crimsonPro.variable} antialiased`}
      >
        <Player imgurl="/doggy/doggy.png" mp3url="/doggy/doggy.mp3" name="Doggy (feat. Love Spells and Truly Young)" artist='Geezer, Kevin Abstract, Dominic Fike' queue={[{ imgurl: "/aftermid/img.png", mp3url: "/aftermid/after.mp3", name: "After Midnight", artist: "AP Dhillon" }]} />
        {children}
      </body>
    </html>
  );
}
